Integrate onboarding availability & polishing the code
hatchways/team-yugioh pull request #155
Opened 2021-02-03 22:04 UTC by alvyjudy

- This PR let's the onboarding component to post the available time and day to the database
- Days are now stored in an array whose number denotes day of the week. `0` is Sunday, `6` is Saturday.
- Solves the warning that says "children props received null" in `SetTimezoneUrl`

I will open another PR to actually use these availability data as that require more work than I anticipated.

2021-02-03 22:28 UTC, kozaktar requested changes
Can you also remove the edit buttons in onboarding dialog since they don't do anything?

2021-02-03 22:33 UTC, alvyjudy commented
Good point Taras!

2021-02-03 22:39 UTC, kozaktar reviewed
Looks good Di!

2021-02-03 22:40 UTC, kozaktar approved these changes

2021-02-04 14:09 UTC, dproc96 approved these changes
Other than my very small suggestion, this looks good to go!

2021-02-04 14:09 UTC, dproc96 commented on server/db/models/User.js
> +    type: mongoose.Schema.Types.Mixed, // {start: "HH:MM", end: "HH:MM"}
You could also define this as such:
```javascript
availableTime: {
  start: String,
  end: String
}
```

2021-02-04 18:33 UTC, alvyjudy commented
@WhoaNellie I have made the edits to store timezone as integer! Please take a look at line 26 on `OnBoarding.js` and line 147 on `SetTimezoneUrl.js`

2021-02-04 20:40 UTC, merged